import { useCallback, useState } from "react";
import { View, ScrollView, TextInput, TouchableOpacity, StyleSheet } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { Ionicons } from "@expo/vector-icons";
import AsyncStorage from "@react-native-async-storage/async-storage";
import Header from "./Header";
import ThemedText from "./ThemedText";
import { useTheme } from "./ThemeContext";
import { KEYS } from "./lifeData";

export default function GoalsScreen(){ const {theme}=useTheme(); const [goals,setGoals]=useState([]); const [title,setTitle]=useState(""); const [target,setTarget]=useState("");
 const load=useCallback(async()=>{try{const r=await AsyncStorage.getItem(KEYS.goals); const parsed = r ? JSON.parse(r) : []; setGoals(Array.isArray(parsed) ? parsed : []);}catch{setGoals([]);}},[]); useFocusEffect(useCallback(()=>{load()},[load]));
 async function save(next){const safe = Array.isArray(next) ? next : []; setGoals(safe); await AsyncStorage.setItem(KEYS.goals, JSON.stringify(safe));}
 async function add(){if(!title.trim()||!Number(target))return; const next=[...goals,{id:Date.now().toString(),title:title.trim(),target:Number(target),progress:0}]; await save(next); setTitle(""); setTarget("");}
 async function increment(g){const next = Array.isArray(goals) ? goals.map(x=>x.id===g.id?{...x,progress:Math.min(x.target,x.progress+1)}:x) : []; await save(next);}
 return <View style={[styles.container,{backgroundColor:theme.background}]}><Header title="Goals" subtitle="Flexible goals without streak pressure"/><ScrollView contentContainerStyle={styles.content}><View style={[styles.card,{backgroundColor:theme.card,borderColor:theme.cardBorder,borderWidth:theme.borderWidth,borderRadius:theme.radius}]}><ThemedText style={styles.title}>Create a goal</ThemedText><TextInput value={title} onChangeText={setTitle} placeholder="e.g. Read 5 books" placeholderTextColor={theme.subText} style={[styles.input,{color:theme.text,backgroundColor:theme.inputBg,borderColor:theme.cardBorder}]}/><TextInput value={target} onChangeText={setTarget} keyboardType="numeric" placeholder="Target number" placeholderTextColor={theme.subText} style={[styles.input,{color:theme.text,backgroundColor:theme.inputBg,borderColor:theme.cardBorder}]}/><TouchableOpacity onPress={add} style={[styles.button,{backgroundColor:theme.primary}]}><ThemedText style={styles.bt}>Add goal</ThemedText></TouchableOpacity></View>{goals.map(g=><View key={g.id} style={[styles.goal,{backgroundColor:theme.card,borderColor:theme.cardBorder,borderWidth:theme.borderWidth,borderRadius:theme.radius}]}><ThemedText style={styles.goalTitle}>{g.title}</ThemedText><ThemedText style={{color:theme.subText}}>{g.progress} / {g.target}</ThemedText><View style={[styles.track,{backgroundColor:theme.inputBg}]}><View style={[styles.fill,{backgroundColor:theme.primary,width:`${Math.min(100,g.progress/g.target*100)}%`}]} /></View><TouchableOpacity onPress={()=>increment(g)} style={[styles.small,{borderColor:theme.cardBorder}]}><Ionicons name="add" size={18} color={theme.primary}/><ThemedText>Add progress</ThemedText></TouchableOpacity></View>)}</ScrollView></View> }
const styles=StyleSheet.create({container:{flex:1},content:{padding:16},card:{padding:18},title:{fontSize:20,fontWeight:"800",marginBottom:12},input:{borderWidth:1,borderRadius:13,padding:13,marginBottom:10},button:{padding:14,borderRadius:13,alignItems:"center"},bt:{color:"#fff",fontWeight:"800"},goal:{padding:18,marginTop:12},goalTitle:{fontSize:17,fontWeight:"800",marginBottom:5},track:{height:9,borderRadius:5,overflow:"hidden",marginVertical:12},fill:{height:9,borderRadius:5},small:{alignSelf:"flex-start",flexDirection:"row",alignItems:"center",gap:6,borderWidth:1,borderRadius:10,paddingHorizontal:10,paddingVertical:7}});
