import { useCallback, useState } from "react";
import { View, ScrollView, Switch, TouchableOpacity, StyleSheet, Alert, Share } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import Header from "./Header";
import ThemedText from "./ThemedText";
import { useTheme } from "./ThemeContext";
import { KEYS } from "./lifeData";
import RestoreBackup from "./RestoreBackup";
import { deleteCloudData } from "./api";

export default function PrivacyScreen(){const {theme}=useTheme();const [settings,setSettings]=useState({autoLockSeconds:30,protectExpenses:false,protectTimeline:false});
 const load=useCallback(async()=>{const r=await AsyncStorage.getItem(KEYS.privacy);if(r)setSettings(JSON.parse(r));},[]);useFocusEffect(useCallback(()=>{load()},[load]));
 async function update(key,value){const next={...settings,[key]:value};setSettings(next);await AsyncStorage.setItem(KEYS.privacy,JSON.stringify(next));}
 async function backup(){const all={};const keys=await AsyncStorage.getAllKeys();const pairs=await AsyncStorage.multiGet(keys);pairs.forEach(([k,v])=>{if(k!=="headerPhoto"){try{all[k]=JSON.parse(v)}catch{all[k]=v}}});await Share.share({title:"LifeTracker Backup",message:JSON.stringify({app:"LifeTracker",version:"2.0",exportedAt:new Date().toISOString(),data:all},null,2)});}
 async function exportCsv(){const raw=await AsyncStorage.getItem("expenses");const rows=raw?JSON.parse(raw):[];const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;const csv=["Date,Title,Category,Type,Amount",...rows.map(r=>[r.date,r.title,r.category,r.type,r.amount].map(esc).join(","))].join("\n");await Share.share({title:"LifeTracker Expenses CSV",message:csv});}
 async function shareReview(){const raw=await AsyncStorage.getItem("expenses");const rows=raw?JSON.parse(raw):[];const now=new Date();const start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-6);const week=rows.filter(r=>r.type!=="income"&&new Date(r.date)>=start);const spent=week.reduce((a,b)=>a+Number(b.amount||0),0);await Share.share({title:"LifeTracker Weekly Review",message:`LifeTracker Weekly Review\n\nSpent: ₹${spent.toFixed(0)}\nGenerated: ${now.toLocaleDateString()}`});}
 async function clear(){Alert.alert("Clear all app data?","This removes your LifeTracker records from this device and your secure cloud backup. This cannot be undone.",[ {text:"Cancel",style:"cancel"},{text:"Clear",style:"destructive",onPress:async()=>{try{await deleteCloudData();}catch{}await AsyncStorage.clear();Alert.alert("Cleared","Your local and cloud LifeTracker data were cleared.")}}]);}
 return <View style={[styles.container,{backgroundColor:theme.background}]}><Header title="Privacy & Backup" subtitle="Your data stays on this device unless you share it"/><ScrollView contentContainerStyle={styles.content}><View style={[styles.card,{backgroundColor:theme.card,borderColor:theme.cardBorder,borderWidth:theme.borderWidth,borderRadius:theme.radius}]}><ThemedText style={styles.title}>Privacy controls</ThemedText><Row title="Lock Money tab with fingerprint" value={settings.protectExpenses} onChange={v=>update("protectExpenses",v)} theme={theme}/><Row title="Lock Timeline tab with fingerprint" value={settings.protectTimeline} onChange={v=>update("protectTimeline",v)} theme={theme}/><ThemedText style={styles.sectionLabel}>Auto-lock</ThemedText><View style={styles.lockOptions}>{[15,30,60,300].map(sec=><TouchableOpacity key={sec} onPress={()=>update("autoLockSeconds",sec)} style={[styles.lockOption,{borderColor:settings.autoLockSeconds===sec?theme.primary:theme.cardBorder,backgroundColor:settings.autoLockSeconds===sec?theme.inputBg:"transparent"}]}><ThemedText>{sec<60?`${sec}s`:`${sec/60}m`}</ThemedText></TouchableOpacity>)}</View><ThemedText style={[styles.hint,{color:theme.subText}]}>App lock and biometric unlock are already available. Auto-lock timing is controlled by the app root.</ThemedText></View><TouchableOpacity onPress={backup} style={[styles.action,{backgroundColor:theme.primary}]}><ThemedText style={styles.actionText}>Export a JSON backup</ThemedText></TouchableOpacity><TouchableOpacity onPress={exportCsv} style={[styles.secondary,{borderColor:theme.cardBorder}]}><ThemedText style={{fontWeight:"800"}}>Share expenses as CSV</ThemedText></TouchableOpacity><TouchableOpacity onPress={shareReview} style={[styles.secondary,{borderColor:theme.cardBorder}]}><ThemedText style={{fontWeight:"800"}}>Share weekly summary</ThemedText></TouchableOpacity><RestoreBackup /><TouchableOpacity onPress={clear} style={[styles.danger,{borderColor:"#E53935"}]}><ThemedText style={{color:"#E53935",fontWeight:"800"}}>Clear all local data</ThemedText></TouchableOpacity></ScrollView></View>}
function Row({title,value,onChange,theme}){return <View style={styles.row}><ThemedText style={{fontWeight:"700"}}>{title}</ThemedText><Switch value={value} onValueChange={onChange} trackColor={{true:theme.primary}}/></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:16},card:{padding:18},title:{fontSize:20,fontWeight:"800",marginBottom:12},sectionLabel:{fontSize:13,fontWeight:"800",marginTop:12},lockOptions:{flexDirection:"row",gap:8,marginTop:8},lockOption:{paddingHorizontal:12,paddingVertical:8,borderWidth:1,borderRadius:10},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:10},hint:{fontSize:12,lineHeight:18,marginTop:8},action:{padding:15,borderRadius:14,alignItems:"center",marginTop:14},secondary:{padding:15,borderRadius:14,alignItems:"center",marginTop:10,borderWidth:1},actionText:{color:"#fff",fontWeight:"800"},danger:{padding:15,borderRadius:14,alignItems:"center",marginTop:10,borderWidth:1}});