export const themes = {
  nature: {
    name: "Living Nature",
    description: "Soft, earthy, calm",
    background: "#EEF3E2",
    card: "#FFFFFF",
    cardBorder: "#DCE5C8",
    borderWidth: 1,
    radius: 28,
    text: "#2F3E2E",
    subText: "#7C8F72",
    inputBg: "#F3F7EA",
    primary: "#4F8A5B",
    accent: "#E9A23B",
    accent2: "#6BA368",
    headerGradient: ["#4F8A5B", "#A7C957"],
    headerText: "#FFFFFF",
    headerBorder: 0,
    tabBar: "#FFFFFF",
    tabActive: "#4F8A5B",
    tabInactive: "#9AAB90",
    fontFamily: "sans-serif-medium",
  },
};